### ISSUE TITLE
Improve LSP extension debugging

### ISSUE THREAD

**Issue by obicons** [obicons/sa4u#19]
I would like to be able to:
* Specify a Docker image to use for analysis in my `.sa4u.json` config
* Create a "debug" mode where the container is not removed on exit (i.e., no `--rm` flag to container startup)

**Comment by Ikutania** [comment]
How would you like the debug mode to be updated?
Should you have access to the server's code to update a variable, should it be in the settings for the sa4u extension, or something else altogether?

**Comment by obicons** [comment]
it should all be in settings, that way we don't forget to to revert code back and accidentally push debugging source upstream

**Comment by obicons** [comment]
The settings for the SA4U extension and the JSON file should have identical functionality
